name: Stage

on:
  pull_request:
    branches:
      - main

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install hc-codesign
        id: codesign
        run: |
          docker login docker.pkg.github.com -u docker -p $GITHUB_TOKEN && \
          docker pull docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION && \
          echo "::set-output name=image::docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION"
        env:
          VERSION: v0
          GITHUB_TOKEN: ${{ secrets.CODESIGN_GITHUB_TOKEN }}
      - name: Install wget & clamAV antivirus scanner
        run : |
           sudo apt-get -qq install -y ca-certificates wget clamav
           wget --version
      - name: Install maldet malware scanner
        run: |
          wget --no-verbose -O maldet-$VERSION.tar.gz https://github.com/rfxn/linux-malware-detect/archive/$VERSION.tar.gz
          sha256sum -c - <<< "$SHA256SUM  maldet-$VERSION.tar.gz"
          sudo mkdir -p maldet-$VERSION
          sudo tar -xzf maldet-$VERSION.tar.gz --strip-components=1 -C maldet-$VERSION
          cd maldet-$VERSION
          sudo ./install.sh
          sudo maldet -u
        env: 
          VERSION: 1.6.4
          SHA256SUM: 3ad66eebd443d32dd6c811dcf2d264b78678c75ed1d40c15434180d4453e60d2
      - name: Build artifacts
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --skip-validate --skip-publish --skip-sign --snapshot --timeout "60m" 
        env:
          SKIP_SIGNING: true
      - name: Upload artifacts to actions workflow
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-artifacts
          path: |
            ${{ github.workspace }}/dist/*.zip
            ${{ github.workspace }}/dist/*.sig
            ${{ github.workspace }}/dist/*SHA256
      - name: Run clamAV antivirus scanner
        run: sudo clamscan ${{ github.workspace }}/dist/
      - name: Run maldet malware scanner
        run: sudo maldet -a ${{ github.workspace }}/dist/
